name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy a Producción
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IP_DEL_SERVIDOR }}
          username: ${{ secrets.USUARIO_SERVIDOR }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/lemp-sites/mateo_torres/prod
            git pull origin main
